--CUSTOMER TABLE
CREATE TABLE CUSTOMER (

    NO NUMBER PRIMARY KEY
    , NAME VARCHAR2(12) NOT NULL
    , PHONE CHAR(13) NOT NULL UNIQUE
    , BIRTH CHAR(10) NOT NULL
    , STAMP NUMBER DEFAULT 0
    , ENROLL TIMESTAMP DEFAULT SYSTIMESTAMP
    , QUIT CHAR(1) DEFAULT 'N' CHECK(QUIT IN ('Y','N'))
    
    );
    SELECT * FROM CUSTOMER;
--COUPON TABLE
CREATE TABLE COUPON (

    NO NUMBER PRIMARY KEY
    ,VARNO NUMBER NOT NULL
    ,GETDATE TIMESTAMP DEFAULT SYSTIMESTAMP
    ,USEDATE TIMESTAMP
    ,USE_CHECK CHAR(1) DEFAULT 'N' CHECK(USE_CHECK IN ('Y','N'))
    ,LIMITDATE CHAR(10) NOT NULL 
    
);


--COU_VAR TABLE
CREATE TABLE COU_VAR (

    VARNO NUMBER PRIMARY KEY
    , NAME VARCHAR2(100) NOT NULL
    , VALUE NUMBER NOT NULL
    , INTRODU VARCHAR2(200) NOT NULL

)
;

-- CUSTOMER Àü¿ë ½ÃÄö½º
CREATE SEQUENCE CUSTOMER_NO_SEQ
INCREMENT BY 1 START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE
NOCACHE
;