-- 카테고리 테이블

SELECT * FROM CATEGORY;

INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'COFFEE'); 
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'NON COFFEE'); 
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'FOODS'); 
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.NEXTVAL, 'GOODS'); 
COMMIT;

-- 메뉴 테이블

SELECT * FROM MENU;

INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '아메리카노', 1);
INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '에스프레소', 1);
INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '카페라떼', 1);
INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '아이스티', 2);
INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '딸기스무디', 2);
INSERT INTO MENU (MN_IDX, MN_NAME, CATEGORY_IDX)
VALUES (MENU_SEQ.NEXTVAL, '망고주스', 2);
COMMIT;

-- 추가옵션 정보 테이블 

SELECT * FROM ADDITIONAL_OPTION;

INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '사이즈', 'TALL', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '사이즈', 'GRANDE', 500);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '사이즈', 'VENTI', 1000);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '온도', 'HOT', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '온도', 'ICE', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '테이크아웃', 'TAKE OUT', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '테이크아웃', 'EAT IN', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '샷추가', '1샷', 500);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '샷추가', '2샷', 1000);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '샷추가', '3샷', 1500);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '얼음양', '적게', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '얼음양', '보통', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '얼음양', '많이', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '휘핑', '없음', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '휘핑', '적게', NULL);
INSERT INTO ADDITIONAL_OPTION 
VALUES (OPTION_SEQ.NEXTVAL, '휘핑', '많이', NULL);

COMMIT;

-- 메뉴/추가옵션 매핑 테이블 (어떤 메뉴에 어떤 추가옵션이 들어가있는가)

SELECT * FROM MENU_ADDITIONAL_OPTION_MAP;

INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (1, 'SIZE');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (1, 'HOT/ICE');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (1, 'TAKE OUT/EAT IN');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (1, 'ADD SHOT');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (1, 'ICE AMOUNT');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (4, 'SIZE');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (4, 'TAKE OUT/EAT IN');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (5, 'SIZE');
INSERT INTO MENU_ADDITIONAL_OPTION_MAP 
VALUES (5, 'TAKE OUT/EAT IN');

COMMIT;
