-- 카테고리 테이블
--DROP TABLE CATEGORY;
------------------------------------------------------------------------
CREATE TABLE CATEGORY(
      CATEGORY_IDX  NUMBER
    , CATEGORY_NAME  VARCHAR2(100)
    , CONSTRAINT CATEGORY_PK PRIMARY KEY(CATEGORY_IDX)
);    
------------------------------------------------------------------------

SELECT * FROM CATEGORY;

INSERT INTO CATEGORY VALUES (1, 'DRINK'); 
INSERT INTO CATEGORY VALUES (2, 'FOOD'); 
INSERT INTO CATEGORY VALUES (3, 'GOODS'); 

COMMIT;

--DROP TABLE CATEGORY;

SELECT CATEGORY_NAME 
FROM CATEGORY WHERE CATEGORY_IDX = 1;









-- 메뉴 테이블
--DROP TABLE MENU;
------------------------------------------------------------------------
CREATE TABLE MENU(
      MN_IDX        NUMBER               PRIMARY KEY
    , CATEGORY_IDX  NUMBER               NOT NULL
    , MN_NAME       VARCHAR(100)         NOT NULL
    , PRICE         NUMBER               NOT NULL
    , DETAIL        VARCHAR(1000)        NOT NULL
    , CAL           NUMBER
    , CAFFEINE      NUMBER
    , CARBOHYDRATE  NUMBER
    , SUGAR         NUMBER
    , FAT           NUMBER
    , PROTEIN       NUMBER
    , NATRIUM       NUMBER
);
--------------------------------------------------------------------------
SELECT * FROM MENU;
-- 메뉴테이블 시퀀스
--DROP SEQUENCE MN_IDX_SEQ;
CREATE SEQUENCE MN_IDX_SEQ
NOCACHE
NOCYCLE;

-- 값은 대충 넣었어요!
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 1, '아메리카노', 4500, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 1, '카페 라떼', 5000, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 1, '돌체 라떼', 3500, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 2, '딸기 쏙 생크림 케이크', 6000, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 2, '피넛 크림 바나나 케이크', 6500, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU 
--VALUES (MN_IDX_SEQ.NEXTVAL, 2, '리치 가나슈 케이크', 5500, '냠냠', 1, 1, 1, 1, 1, 1, 1);
--INSERT INTO MENU (MN_IDX, CATEGORY_IDX, MN_NAME, PRICE, DETAIL)
--VALUES (MN_IDX_SEQ.NEXTVAL, 3, '워드마크 스퀘어 머그', 15000, '머그머그');
--INSERT INTO MENU (MN_IDX, CATEGORY_IDX, MN_NAME, PRICE, DETAIL)
--VALUES (MN_IDX_SEQ.NEXTVAL, 3, '크림 사이렌 스퀘어 머그', 18000, '컵');
--INSERT INTO MENU (MN_IDX, CATEGORY_IDX, MN_NAME, PRICE, DETAIL)
--VALUES (MN_IDX_SEQ.NEXTVAL, 3, '그린 사이렌 스퀘어 머그', 15000, '컵컵');









-- 추가옵션 정보 테이블 
DROP TABLE ADDITIONAL_OPTION;
------------------------------------------------------------------------
CREATE TABLE ADDITIONAL_OPTION(
      ADI_OPT_IDX     NUMBER          PRIMARY KEY
    , ADI_OPT_NAME    VARCHAR2(100)   NOT NULL
    , ADI_OPT_CHOICE  VARCHAR2(100)   NOT NULL
    , ADI_OPT_PRICE   NUMBER
);
------------------------------------------------------------------------
-- 추가옵션인덱스_시퀀스
CREATE SEQUENCE ADI_OPT_IDX_SEQ
NOCACHE
NOCYCLE;
--DROP SEQUENCE ADI_OPT_IDX_SEQ;

SELECT * FROM ADDITIONAL_OPTION;

--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, 'HOT/ICE', 'HOT', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, 'HOT/ICE', 'ICE', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, 'SIZE', 'TALL', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, 'SIZE', 'GRANDE', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, 'SIZE', 'VENTI', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '컵 선택', '매장컵', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '컵 선택', '개인컵', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '컵 선택', '일회용컵', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '샷 추가', '1샷', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '샷 추가', '2샷', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '샷 추가', '3샷', 500);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '얼음 양', '적게', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '얼음 양', '보통', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '얼음 양', '많이', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '휘핑크림', '적게', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '휘핑크림', '보통', NULL);
--INSERT INTO ADDITIONAL_OPTION
--VALUES (ADI_OPT_IDX_SEQ.NEXTVAL, '휘핑크림', '많이', NULL);










-- 메뉴/추가옵션 매핑 테이블
--DROP TABLE MENU_ADDITIONAL_OPTION_MAP;
------------------------------------------------------------------------
CREATE TABLE MENU_ADDITIONAL_OPTION_MAP (
      MN_IDX          NUMBER          NOT NULL 
    , ADI_OPT_IDX     NUMBER          NOT NULL
);
------------------------------------------------------------------------


SELECT * 
FROM MENU_ADDITIONAL_OPTION_MAP;

INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 1);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 3);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 6);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 9);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 12);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (1, 15);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 1);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 3);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 6);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 9);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 12);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (2, 15);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 1);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 3);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 6);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 9);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 12);
INSERT INTO MENU_ADDITIONAL_OPTION_MAP VALUES (3, 15);









-- 어떤 메뉴에 어떤 추가옵션이 매핑되어있는가 조회
SELECT ROWNUM,
     MN_NAME AS 메뉴명
    , AO.ADI_OPT_NAME AS 옵션명
FROM MENU M
INNER JOIN MENU_ADDITIONAL_OPTION_MAP MAO ON M.MN_IDX = MAO.MN_IDX
INNER JOIN ADDITIONAL_OPTION AO ON AO.ADI_OPT_IDX = MAO.ADI_OPT_IDX
WHERE M.MN_NAME = '아메리카노';

--COMMIT;

SELECT ROWNUM,
 MN_NAME AS 메뉴명 
, AO.ADI_OPT_NAME AS 옵션명 
FROM MENU M 
INNER JOIN MENU_ADDITIONAL_OPTION_MAP MAO ON M.MN_IDX = MAO.MN_IDX 
INNER JOIN ADDITIONAL_OPTION AO ON AO.ADI_OPT_IDX = MAO.ADI_OPT_IDX 
WHERE M.MN_IDX = 1
ORDER BY ROWNUM;




