INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 10000);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 5000);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 4000);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 8000);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/26', 10000);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/04/25', 8000);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 12000, 2000, 0);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 8000, 1000, 3000);
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 8000, 0, 4000);

SELECT * FROM ORDER_GROUP;

INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 5000, 1);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 5000, 2);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 1, 4000, 3);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 1, 4000, 4);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 1, 4000, 4); 

INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 10000, 5);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 4000, 5);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 3, 2, 12000, 6);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 2, 12000, 7);

SELECT * FROM ORDER_ITEM;

COMMIT;