INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/04/23', 6000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 6000, 1);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/04/25', 3000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 3000, 2);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/20', 3000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 3000, 3);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/20', 10300);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 1, 4000, 4);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 14, 1, 6300, 4);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/21', 12300);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 6, 1, 6300, 5); 
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 6000, 5);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/22', 16000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 40, 1, 12000, 6);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 2, 1, 4000, 6);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/23', 13700);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 3, 2, 8000, 7);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 16, 1, 5700, 7);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/23', 12200);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 21, 1, 6200, 8);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 6000, 8);

--5월24일 아메리카노 1000원 할인
INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/24', 7700, 0, 1000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 3000, 9);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 16, 1, 5700, 9);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/24', 6500, 0, 1000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 1, 3000, 10);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 17, 1, 4500, 10);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/24', 10500, 0, 3000);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 3, 9000, 11);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 17, 1, 4500, 11);
--

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 17400, 0, 0);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 1, 2, 6000, 12);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 3, 1, 5700, 12);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 16, 1, 5700, 12);

INSERT INTO ORDER_GROUP(GROUP_NO, ORDER_DATE, TOTAL_PRICE, USE_POINT, DISCOUNT_PRICE) VALUES (GROUP_SEQ.NEXTVAL, '22/05/25', 18900, 0, 0);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 12, 2, 12600, 13);
INSERT INTO ORDER_ITEM(NO, MN_IDX, ITEM_NUM, ITEM_PRICE, GROUP_NO) VALUES (ITEM_SEQ.NEXTVAL, 15, 1, 6300, 13);


COMMIT;