
-- 로그인 테이블 생성
CREATE TABLE LOGIN(
    NO NUMBER PRIMARY KEY
    , ID VARCHAR2(30) NOT NULL UNIQUE
    , PWD VARCHAR2(30) NOT NULL
    , NAME VARCHAR2(30) NOT NULL UNIQUE
    , GENDER CHAR(10) NOT NULL
    , BIRTH CHAR(10) NOT NULL
    , PHONE CHAR(13) NOT NULL UNIQUE
    , EMAIL VARCHAR2(30) NOT NULL UNIQUE
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
    , QUIT_YN CHAR(1) DEFAULT 'N' CHECK(QUIT_YN IN ('Y','N'))
);


-- 로그인 테이블 삭제
--DROP TABLE LOGIN;

-- 데이터 생성
INSERT INTO LOGIN(NO, ID, PWD, NAME, GENDER, BIRTH, PHONE, EMAIL) 
VALUES(1, 'HONG01', '1234', '홍길동', '남', TO_CHAR('2002/06/25'), '010-1234-5678', 'HONGG@NAVER.COM');

-- 데이터 삭제
--DELETE FROM LOGIN
--WHERE NO = 2;

-- 시퀀스 생성
CREATE SEQUENCE LOGIN_NO_SEQ
INCREMENT BY 1 -- 증감숫자
START WITH 2 -- 시작값
MINVALUE 1 -- 최소값
MAXVALUE 999 -- 최대값
NOCYCLE -- CYCLE --순환여부
NOCACHE -- 캐시 여부 (사이즈)
;

-- 시퀀스 삭제
--DROP SEQUENCE LOGIN_NO_SEQ;

-- 조회
SELECT * FROM LOGIN
ORDER BY ENROLL_DATE;

COMMIT;