-- 주문아이템 테이블
CREATE TABLE ORDER_ITEM (
      NO NUMBER PRIMARY KEY
    , MN_IDX NUMBER NOT NULL
    , ITEM_PRICE NUMBER NOT NULL
    , ITEM_NUM NUMBER DEFAULT 1 NOT NULL
    , GROUP_NO NUMBER NOT NULL
    
    , CONSTRAINT GROUP_FK FOREIGN KEY(NO) REFERENCES ORDER_GROUP(GROUP_NO)
);

-- 주문 테이블
CREATE TABLE ORDER_GROUP (
      GROUP_NO NUMBER PRIMARY KEY
    , ORDER_DATE DATE DEFAULT SYSDATE NOT NULL
    , U_NUM NUMBER
    , TOTAL_PRICE NUMBER NOT NULL
    , USE_POINT NUMBER DEFAULT 0 NOT NULL
    , DISCOUNT_PRICE NUMBER DEFAULT 0 NOT NULL
    
    , CONSTRAINT CUSTOMER_FK FOREIGN KEY(U_NUM) REFERENCES CUSTOMER(NUM)
);

-- 주문아이템_추가옵션
CREATE TABLE ORDER_ITEM_ADD (
      ITEM_NO NUMBER NOT NULL
    , ADI_OPT_IDX NUMBER NOT NULL
    
    , CONSTRAINT ITEM_FK FOREIGN KEY(ITEM_NO) REFERENCES ORDER_ITEN(NO) ON DELETE CASCADE
    , CONSTRAINT ADD_FK FOREIGN KEY(ADI_OPT_IDX) REFERENCES ADDITIONAL_OPTION(ADI_OPT_IDX)
);

